CREATE OR REPLACE PROCEDURE SP_UPDATE_PRODUTO(
    P_ID   produto2.ID%TYPE,
    P_NOME   produto2.NOME%TYPE) 
    AS 
BEGIN
  UPDATE PRODUTO2 SET NOME =  P_NOME WHERE ID = P_ID;
     COMMIT;
END SP_UPDATE_PRODUTO;